### ISSUE TITLE
TLS configuration issue

### ISSUE THREAD

**Issue by Shravankumark** [Lowess/helm-charts#12]
I am using below config in values.yaml and running into an issue.
Would someone be able to tell if there is any issue in the config?

 ## Maps to [client-profile] section in burrow.toml
    clientProfile:
      ## clientProfile configures a Kafka profile to use by Burrow consumer.
      main:
        kafkaVersion: "2.2.1"
        clientId: "burrow-test"
        tls: "msk-mTLS"

    tls: {}
      msk-mTLS:
        certFile: "/tmp/client_cert.pem"
        keyFile: "/tmp/private_key.pem"
        caFile: "/tmp/truststore.pem"

Error:
Error: render error in "burrow/templates/burrow-deployment.yaml": template: burrow/templates/burrow-deployment.yaml:16:28: executing "burrow/templates/burrow-deployment.yaml" at <include (print $.Template.BasePath "/burrow-configmap.yaml") .>: error calling include: template: burrow/templates/burrow-configmap.yaml:30:18: executing "burrow/templates/burrow-configmap.yaml" at <.Values.burrow.config.tls>: nil pointer evaluating interface {}.burrow

**Comment by Shravankumark** [comment]
Correction in above config:

clientProfile:
  ## clientProfile configures a Kafka profile to use by Burrow consumer.
  main:
    kafkaVersion: "2.2.1"
    clientId: "burrow-test"
    tls: "msk-mTLS"

tls:
  msk-mTLS:
    certFile: "/tmp/client_cert.pem"
    keyFile: "/tmp/private_key.pem"
    caFile: "/tmp/truststore.pem"

**Comment by Lowess** [comment]
Released as burrow-0.1.5

**Comment by Lowess** [comment]
Released as `burrow-0.1.5`

**Comment by Lowess** [comment]
`Released as burrow-0.1.5`
