### ISSUE TITLE
Add possibility to specify 'client-profile' for clusters

### ISSUE THREAD

**Issue by korjek** [Lowess/helm-charts#20]
According to Burrow configuration [documentation](https://github.com/linkedin/Burrow/wiki/Cluster-Kafka#configuration), it's possible to specify `client-profile` for cluster.

But that's not possible with the current [chart](https://github.com/Lowess/helm-charts/blob/b2994ce1969e0b8f4838baedef741f23677d6473/charts/burrow/templates/burrow-configmap.yaml#L43-L49) (it's [possible](https://github.com/Lowess/helm-charts/blob/b2994ce1969e0b8f4838baedef741f23677d6473/charts/burrow/templates/burrow-configmap.yaml#L59) to specify `client-profile` for `consumer` though).

Please add support of this configuration option.

We are glad to contribute and prepare PR.

**Comment by Lowess** [comment]
HI @korjek please prep a PR I will be happy to review and release

**Comment by korjek** [comment]
Hi @Lowess 
PR is submitted
https://github.com/Lowess/helm-charts/pull/22

**Comment by korjek** [comment]
PR was merged
