### ISSUE TITLE
Helm repo giving 404 error

### ISSUE THREAD

**Issue by janhoy** [Lowess/helm-charts#25]
https://lowess.github.io/helm-charts/ does not work
![Skjermbilde 2022-03-08 kl  14 31 37](https://user-images.githubusercontent.com/409128/157247818-c48818f2-7091-4f67-bdde-ce29e7bf0705.png)

**Comment by Lowess** [comment]
There is no index.html hence why you are getting 404.

The repo is operational as you can see here
https://lowess.github.io/helm-charts/index.yaml

Le mar. 8 mars 2022 à 14:32, Jan Høydahl ***@***.***> a
écrit :

**Comment by janhoy** [comment]
Ok. The docs use the short URL without index.yaml. Do you think it will work for all tools, such as ArgoCD helm support, i.e. that they are smart enough to append index.yaml? I'll give it a try...

**Comment by janhoy** [comment]
It worked, closing
