### ISSUE TITLE
Support Kubernetes 1.22

### ISSUE THREAD

**Issue by janhoy** [Lowess/helm-charts#26]
Trying the helm chart for Zoonavigator. To support k8s 1.22, it means using `networking.k8s.io/v1` for Ingress. I'm getting 
> unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

~Downgrading my k8s cluster to 1.21 for now...~ My client's clusters have upgraded to 1.22 so need to fix this.

**Comment by Lowess** [comment]
Hi @janhoy PRs are welcome :)

**Comment by Lowess** [comment]
A new version of Zoonavigator has been released with support for 1.22 https://github.com/Lowess/helm-charts/releases/tag/zoonavigator-0.1.3
