### ISSUE TITLE
Missing IngressClassName field in ingress templates in zoonavigator (and possibly others)

### ISSUE THREAD

**Issue by piotrrybicki** [Lowess/helm-charts#47]
Hi.

In the ingress template, you are defining it's class via annotation which is depreciated method.
https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

On newer k8s installations, there is no way of definig ingress class (annotation is ignored).

**Comment by Lowess** [comment]
Fixed in version `zoonavigator-0.1.4`

**Comment by piotrrybicki** [comment]
unfortunatelly, stil not working fine.

`Ingress.extensions "zoonavigator" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "XXX": can not be set when the class field is also set.`
